codecov:
    require_ci_to_pass: true

comment: false

coverage:
    status:
        project:
            default: false
            patch: false
            tests:
                target: 100%
                paths: "tests/"
            browser:
                paths: "src/"