comment: false

coverage:
  status:
    project:
      users:
        paths:
          - tests/users
          - app/components/user*
      products:
        paths:
          - tests/products
          - app/components/product*
