comment: false
coverage:
    status:
        patch: off
        project:
            default:
                informational: true
                only_pulls: true
                paths:
                    - src
