name: Build

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Install
      shell: bash
      run: sudo apt install lcov

    - name: Build
      shell: bash
      run: ./build.sh debug
    
    - name: Run Tests
      shell: bash
      run: ./out/test_vl
    
    - name: Run gcov
      shell: bash
      run: |
        for full_path in `find ./src -name "*.c"`; 
        do 
          filename=$(basename $full_path)
          gcov -pb -r -o ./out test_vl-$filename
          echo
        done
        ls -la

    - name: Run lcov
      shell: bash
      run: |
        lcov --capture --directory . --output-file coverage.info
        genhtml coverage.info --output-directory out
        cat ./out/index.html
