name: Build

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Build
      shell: bash
      run: ./build.sh debug

    - name: Run Tests
      shell: bash
      run: ./out/test_vl

    - name: Run gcov
      shell: bash
      run: |
        echo "## Automated gcov report" >> comment-body.md
        for full_path in `git diff ${{github.base_ref}} ${{github.head_ref}} --name-only | grep '\.c$'`; 
        do 
          filename=$(basename $full_path)
          echo "### ${filename}" >> comment-body.md
          echo "```" >> comment-body.md
          gcov -n -o ./out test_vl-$filename >> comment-body.md
          echo "```" >> comment-body.md
          echo >> comment-body.md
        done
        cat comment-body.md

    - name: Find Comment
      uses: peter-evans/find-comment@v3
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Automated gcov report

    - name: Create comment
      if: steps.fc.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: 'comment-body.md'

    - name: Update comment
      if: steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: 'comment-body.md'