name: Build

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Build
      shell: bash
      run: ./build.sh debug

    - name: Run Tests
      shell: bash
      run: ./out/test_vl

    - name: Remove test coverage files
      shell: bash
      run: find ./out/ -name "test_vl-test_*" -type f -delete

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        disable_telem: true
        token: ${{ secrets.CODECOV_TOKEN }}