name: Build

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Build
      shell: bash
      run: ./build.sh debug

    - name: Run Tests
      shell: bash
      run: ./out/test_vl

    - name: Run gcov
      shell: bash
      run: |
        for full_path in `find ./src -name "*.c"`; 
        do 
          filename=$(basename $full_path)
          gcov -pb -r -o ./out test_vl-$filename
          echo
        done
        ls -la

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        disable_telem: true
        disable_search: true
        files: tokenizer.c.gcov
        working-directory: ${{ github.workspace }}
        token: ${{ secrets.CODECOV_TOKEN }}