name: Build

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Build
      shell: bash
      run: ./build.sh debug
    
    - name: Run Tests
      shell: bash
      run: ./out/test_vl
    
    - name: Run gcov
      shell: bash
      run: |
        for filename in `find ./src -name "*.c"`; 
        do 
          echo $filename
          gcov -pb -r -o ./out $filename
        done
        ls -la
